"""Writing `docs/reference/destinations.md` -- the record of which exit each category drives to.

The document is generated rather than hand-maintained, for the reason the house rules give: never
quote a measured figure, re-measure it. Every number in it comes from a reset on this simulator,
so regenerating it after a MetaDrive bump is how a change in block shape becomes visible.
"""

from __future__ import annotations

from pathlib import Path

from scenariobank.categories import CATEGORIES, SEEDS, step_budget
from scenariobank.sockets import survey


def measure_road_variety(
    seeds: tuple[int, ...] = SEEDS,
) -> tuple[dict[str, list[str]], dict[str, tuple[int, int, float] | None]]:
    """Fingerprint each block sequence at each seed, **and** measure how alike the closest two are.

    A seed is assumed to mean a different road, and for three of the five sequences it does
    not. Measuring it here, in the generated document, is what keeps that from being a
    surprise in Phase 2 -- or worse, an unexamined assumption in `CONTRACT.md`.

    Two answers, because the digest alone was misread for a while. It counts roads that are not
    *identical*, which called `curve` seeds 0 and 4 distinct at a 7% gap and `roundabout` seeds 0
    and 4 distinct at no measurable gap at all. `variety.closest_pair` says how close the closest
    two actually are, off the same resets.
    """
    from metadrive.envs.metadrive_env import MetaDriveEnv

    from scenariobank.config import base_config
    from scenariobank.fingerprint import lane_geometry_digest, road_shape
    from scenariobank.variety import closest_pair

    sequences = sorted({category.block_seq for category in CATEGORIES.values()})
    variety, closest = {}, {}
    for block_seq in sequences:
        env = MetaDriveEnv(
            base_config(map=block_seq, start_seed=min(seeds), num_scenarios=len(seeds))
        )
        try:
            digests, shapes = [], {}
            for seed in seeds:
                env.reset(seed=seed)
                digests.append(lane_geometry_digest(env.engine.current_map, length=10))
                shapes[seed] = road_shape(env.engine.current_map)
            variety[block_seq] = digests
            closest[block_seq] = closest_pair(shapes)
        finally:
            env.close()
    return variety, closest

HEADER = """# Destinations

Generated by `scenariobank destinations`. Do not edit by hand -- every figure here is
measured on the simulator `scenariobank doctor` reports, and regenerating after a MetaDrive bump
is how a change in block geometry becomes visible.

Angles are degrees from the ego's spawn heading, counter-clockwise-positive, so **positive is a
left turn** (`straight_lane.py:56`). `route_length` is `navigation.total_length` with the
destination pinned, which also proves the destination is reachable and not merely named.

**Two different angles appear below.** The resolved-destination table reports the *final heading*,
`wrap_to_pi`'d -- correct for choosing an exit, and what `ExitRule` matches against. "Turn taken"
reports **total rotation along the driven route**, which is not wrapped. They agree everywhere
except a route that sweeps past 180 degrees, where the wrapped one folds and changes sign: `curve`
seed 0 turns +239.5 degrees left and its final heading reads -120.5.
"""


def build_rows(seeds: tuple[int, ...] = SEEDS) -> dict[str, list[dict]]:
    """Resolve and measure every category at every seed."""
    return {name: survey(category, seeds) for name, category in CATEGORIES.items()}


def _spawn_lane_section(rows: dict[str, list[dict]], seeds: tuple[int, ...]) -> list[str]:
    """The spawn lane per seed -- the one thing a fixed road still varies.

    `random_spawn_lane_index` is left on deliberately (`config.base_config`), so the lane is a
    seeded draw rather than a constant. Measurement says it depends only on the seed, because
    every map is `lane_num=3` -- but that is **checked here rather than assumed**, and the full
    per-category table is emitted if it ever stops being true.
    """
    lanes = {
        name: [row["spawn_lane"] for row in category_rows]
        for name, category_rows in rows.items()
    }
    header = [
        "",
        "## Spawn lane",
        "",
        "Which of the three lanes the ego starts in. Drawn by `random_spawn_lane_index`, which",
        "this bank deliberately leaves on -- for `X` it is the *only* thing that differs between",
        "the five seeds, since the road is identical at all five. `route_length` is measured on a",
        "reference lane and so does not reflect it.",
        "",
    ]
    shared = next(iter(lanes.values()))
    if all(seq == shared for seq in lanes.values()):
        return header + [
            "| | " + " | ".join(f"seed {s}" for s in seeds) + " |",
            "|---|" + "---|" * len(seeds),
            "| every category | " + " | ".join(str(lane) for lane in shared) + " |",
            "",
            "Identical for every block sequence -- the draw is `randint(lane_num)` and every "
            f"map is `lane_num=3`, so it depends only on the seed. {len(set(shared))} distinct "
            f"starting lanes across these {len(seeds)} seeds.",
        ]
    return header + [
        "| category | " + " | ".join(f"seed {s}" for s in seeds) + " |",
        "|---|" + "---|" * len(seeds),
        *(
            f"| `{name}` | " + " | ".join(str(lane) for lane in seq) + " |"
            for name, seq in lanes.items()
        ),
        "",
        "**The spawn lane is no longer seed-only.** It used to depend on nothing but the seed;",
        "if this table is not uniform, a block sequence has changed its lane count.",
    ]


def _turn_pair_section(rows: dict[str, list[dict]], seeds: tuple[int, ...]) -> list[str]:
    """Which direction each `Curve` block turns, per seed.

    `CC` is two curves drawn independently, so the pair is the property that matters: two lefts
    and two rights are not enough on their own, the seeds have to reach left-then-right and
    right-then-left as well. `tests/unit/test_categories.py` asserts the coverage.
    """
    curved = {
        name: category_rows
        for name, category_rows in rows.items()
        if any(row["turn_pairs"] for row in category_rows)
    }
    if not curved:
        return []
    lines = [
        "",
        "## Curve direction pairs",
        "",
        "One letter per `Curve` block on the route, in order. The two blocks of `CC` draw their",
        "direction independently (`pg_space.py:284-289`), so the pair -- not the net angle -- is",
        "what says whether the seeds cover the manoeuvre.",
        "",
        "**A letter describes an arc, not a whole block.** A MetaDrive `Curve` block is an arc",
        "*and* a trailing straight of drawn length: `create_bend_straight` returns both and",
        "`pgblock/curve.py` builds them as its part 1 and part 2. So a `CC` road is straight,",
        "arc, straight, arc, straight -- the straights between and after the bends are part of",
        "the same two blocks, not extra ones.",
        "",
        "| category | " + " | ".join(f"seed {s}" for s in seeds) + " | combinations |",
        "|---|" + "---|" * len(seeds) + "---|",
    ]
    for name, category_rows in curved.items():
        signatures = [row["turn_pairs"] for row in category_rows]
        distinct = len(set(signatures))
        possible = 2 ** len(signatures[0])
        marker = "" if distinct == possible else "  **<**"
        lines.append(
            f"| `{name}` | "
            + " | ".join(f"`{sig}`" for sig in signatures)
            + f" | {distinct}/{possible}{marker} |"
        )
    lines += [
        "",
        "`L` is a left-turning block, `R` a right-turning one, measured from the built geometry",
        "rather than from `Parameter.dir` -- the map is mirrored (`handedness.py`), and a",
        "parameter reading would label every turn backwards.",
        "",
        "Read the letters, not the picture. The ego always spawns heading **due east**, so it",
        "drives rightward in every figure -- but where that spawn lands in the frame moves with",
        "the seed, and `curve` seeds 2 and 3 start at the *top* and bend downward while 0, 1 and",
        "4 start at the bottom and bend up. A map read from the wrong end reverses every turn in",
        "it. `scenariobank inspect` and the bank's thumbnails draw the spawn arrow for exactly",
        "this reason.",
    ]
    return lines


def _closest_pair_section(
    closest: dict[str, tuple[int, int, float] | None] | None,
) -> list[str]:
    """How alike the two most similar seeds of each sequence are -- the check a hash cannot make.

    `lane_geometry_digest` is an equality test. `fingerprint.shape_gap` is the coarse similarity
    measure that answers the question the distinct-roads count was being read as answering.
    """
    if not closest:
        return []
    from scenariobank.variety import NEAR_DUPLICATE

    lines = [
        "",
        "### How alike are the closest two?",
        "",
        "Measured by `fingerprint.shape_gap`: the worst relative difference in total lane length",
        "and in map extent. Coarse on purpose -- it catches near-twins, which is what the digest",
        "above cannot do.",
        "",
        "| block_seq | closest pair | gap | |",
        "|---|---|---|---|",
    ]
    flagged = False
    for block_seq, pair in sorted(closest.items()):
        if pair is None:
            continue
        a, b, gap = pair
        near = gap < NEAR_DUPLICATE
        flagged = flagged or near
        note = "**near-duplicate**" if near else ""
        lines.append(f"| `{block_seq}` | seeds {a} and {b} | {gap * 100:.0f}% | {note} |")
    if flagged:
        lines += [
            "",
            f"A gap under {NEAR_DUPLICATE * 100:.0f}% means those two seeds are the same drive",
            "however different their hashes are. `scenariobank seeds --category <name>` ranks",
            "other seeds by how much they would actually add, and `generate --seeds` and",
            "`replace` are how you act on it. The seeds are a choice, not a constant.",
        ]
    return lines


def render(
    rows: dict[str, list[dict]],
    seeds: tuple[int, ...] = SEEDS,
    variety: dict[str, list[str]] | None = None,
    closest: dict[str, tuple[int, int, float] | None] | None = None,
) -> str:
    """Render the measured rows as the reference document."""
    lines = [HEADER, "## Resolved destination per category and seed", ""]
    lines.append("| category | block_seq | rule | " + " | ".join(f"seed {s}" for s in seeds) + " |")
    lines.append("|---|---|---|" + "---|" * len(seeds))
    for name, category in CATEGORIES.items():
        cells = [f"`{row['destination']}` {row['angle_deg']:+.0f}deg" for row in rows[name]]
        lines.append(
            f"| `{name}` | `{category.block_seq}` | `{category.exit_rule.value}` | "
            + " | ".join(cells)
            + " |"
        )

    lines += ["", "## Route length and step budget", ""]
    lines.append("| category | shortest | longest | `max_steps` | budget at longest |")
    lines.append("|---|---|---|---|---|")
    for name, category in CATEGORIES.items():
        lengths = [row["route_length_m"] for row in rows[name]]
        earned = step_budget(max(lengths))
        note = "" if category.max_steps >= earned else "  **under budget**"
        lines.append(
            f"| `{name}` | {min(lengths):.1f} m | {max(lengths):.1f} m | "
            f"{category.max_steps} | {earned}{note} |"
        )

    lines += [
        "",
        "**budget at longest** is `step_budget(longest route)`: length / (6 m/s x 0.1 s per step)",
        "x 1.5, rounded up to 20. `max_steps` is never below it and may sit above it where the",
        "category has a reason -- `tollgate` caps its own lanes at 3 m/s (`tollgate.py:68`), so",
        "the toll section is driven at half the reference speed and is charged for twice. A cap",
        "is provisional until Phase 4b measures what a policy actually needs.",
        "",
        "## Turn taken",
        "",
        "Total rotation along the route, unwrapped -- see the note above.",
        "",
        "| category | " + " | ".join(f"seed {s}" for s in seeds) + " |",
        "|---|" + "---|" * len(seeds),
    ]
    for name in CATEGORIES:
        cells = [f"{row['turn']} {row['net_rotation_deg']:+.1f}deg" for row in rows[name]]
        lines.append(f"| `{name}` | " + " | ".join(cells) + " |")

    lines += _spawn_lane_section(rows, seeds) + _turn_pair_section(rows, seeds)

    if variety is not None:
        lines += [
            "",
            "## Distinct roads per block sequence",
            "",
            "A seed does not always mean a different road. Fingerprints are of the drivable",
            "surface -- every lane centreline, sampled -- not of `get_meta_data()`, which",
            "carries `map_config.seed` and would make every road look unique.",
            "",
            "| block_seq | distinct roads | " + " | ".join(f"seed {s}" for s in seeds) + " |",
            "|---|---|" + "---|" * len(seeds),
        ]
        for block_seq, digests in sorted(variety.items()):
            marker = "" if len(set(digests)) == len(seeds) else "  **<**"
            lines.append(
                f"| `{block_seq}` | {len(set(digests))}/{len(seeds)}{marker} | "
                + " | ".join(f"`{d}`" for d in digests)
                + " |"
            )
        total = sum(len(set(d)) for d in variety.values())
        lines += [
            "",
            f"**{total} distinct roads across the {len(CATEGORIES) * len(seeds)} scenarios, and "
            "that number flatters the bank.**",
            "It counts roads that are not *identical*. Two seeds can draw roads a few percent",
            "apart -- near enough that their thumbnails are the same picture -- and a digest",
            "calls them two roads. The next table is the honest one.",
        ]
        lines += _closest_pair_section(closest)
        lines += [
            "",
            "`X` has no seeded degree of freedom left: `StdInterSection` fixes its radius and the",
            "map pins `lane_num=3` and `lane_width=3.5`. Accepted deliberately -- the five seeds",
            "of an intersection category vary the scene, not the road. Phase 2 must therefore not",
            f"assert {len(CATEGORIES) * len(seeds)} distinct roads.",
            "",
            "Those five runs are still not identical, though: the ego starts in a different lane",
            "(see **Spawn lane**), which is the only thing distinguishing them until Phase 4's",
            "options arrive.",
        ]
    lines.append("")
    return "\n".join(lines)


def write(path: Path, seeds: tuple[int, ...] = SEEDS) -> Path:
    """Measure everything and write the document. Costs two env builds per category per seed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    variety, closest = measure_road_variety(seeds)
    path.write_text(render(build_rows(seeds), seeds, variety, closest))
    return path
