"""Writing `docs/reference/destinations.md` -- the record of which exit each category drives to.

The document is generated rather than hand-maintained, for the reason the house rules give: never
quote a measured figure, re-measure it. Every number in it comes from a reset on this simulator,
so regenerating it after a MetaDrive bump is how a change in block shape becomes visible.
"""

from __future__ import annotations

from pathlib import Path

from scenariobank.categories import CATEGORIES, SEEDS, step_budget
from scenariobank.sockets import survey


def measure_road_variety(seeds: tuple[int, ...] = SEEDS) -> dict[str, list[str]]:
    """Fingerprint the drivable surface of each block sequence at each seed.

    A seed is assumed to mean a different road, and for three of the five sequences it does
    not. Measuring it here, in the generated document, is what keeps that from being a
    surprise in Phase 2 -- or worse, an unexamined assumption in `CONTRACT.md`.
    """
    from metadrive.envs.metadrive_env import MetaDriveEnv

    from scenariobank.config import base_config

    sequences = sorted({category.block_seq for category in CATEGORIES.values()})
    variety = {}
    for block_seq in sequences:
        env = MetaDriveEnv(
            base_config(map=block_seq, start_seed=min(seeds), num_scenarios=len(seeds))
        )
        try:
            variety[block_seq] = [
                _digest_after_reset(env, seed) for seed in seeds
            ]
        finally:
            env.close()
    return variety


def _digest_after_reset(env, seed: int) -> str:
    from scenariobank.fingerprint import lane_geometry_digest

    env.reset(seed=seed)
    return lane_geometry_digest(env.engine.current_map, length=10)

HEADER = """# Destinations

Generated by `scenariobank destinations`. Do not edit by hand -- every figure here is
measured on the simulator `scenariobank doctor` reports, and regenerating after a MetaDrive bump
is how a change in block geometry becomes visible.

Angles are degrees from the ego's spawn heading, counter-clockwise-positive, so **positive is a
left turn** (`straight_lane.py:56`). `route_length` is `navigation.total_length` with the
destination pinned, which also proves the destination is reachable and not merely named.
"""


def build_rows(seeds: tuple[int, ...] = SEEDS) -> dict[str, list[dict]]:
    """Resolve and measure every category at every seed."""
    return {name: survey(category, seeds) for name, category in CATEGORIES.items()}


def render(
    rows: dict[str, list[dict]],
    seeds: tuple[int, ...] = SEEDS,
    variety: dict[str, list[str]] | None = None,
) -> str:
    """Render the measured rows as the reference document."""
    lines = [HEADER, "## Resolved destination per category and seed", ""]
    lines.append("| category | block_seq | rule | " + " | ".join(f"seed {s}" for s in seeds) + " |")
    lines.append("|---|---|---|" + "---|" * len(seeds))
    for name, category in CATEGORIES.items():
        cells = [f"`{row['destination']}` {row['angle_deg']:+.0f}deg" for row in rows[name]]
        lines.append(
            f"| `{name}` | `{category.block_seq}` | `{category.exit_rule.value}` | "
            + " | ".join(cells)
            + " |"
        )

    lines += ["", "## Route length and step budget", ""]
    lines.append("| category | shortest | longest | `max_steps` | budget at longest |")
    lines.append("|---|---|---|---|---|")
    for name, category in CATEGORIES.items():
        lengths = [row["route_length_m"] for row in rows[name]]
        earned = step_budget(max(lengths))
        note = "" if category.max_steps >= earned else "  **under budget**"
        lines.append(
            f"| `{name}` | {min(lengths):.1f} m | {max(lengths):.1f} m | "
            f"{category.max_steps} | {earned}{note} |"
        )

    lines += [
        "",
        "`max_steps` is `step_budget(longest route)`: length / (6 m/s x 0.1 s per step) x 1.5,",
        "rounded up to 20. Provisional until Phase 4b measures what a policy actually needs.",
        "",
        "## Turn taken",
        "",
        "| category | " + " | ".join(f"seed {s}" for s in seeds) + " |",
        "|---|" + "---|" * len(seeds),
    ]
    for name in CATEGORIES:
        lines.append(f"| `{name}` | " + " | ".join(row["turn"] for row in rows[name]) + " |")

    if variety is not None:
        lines += [
            "",
            "## Distinct roads per block sequence",
            "",
            "A seed does not always mean a different road. Fingerprints are of the drivable",
            "surface -- every lane centreline, sampled -- not of `get_meta_data()`, which",
            "carries `map_config.seed` and would make every road look unique.",
            "",
            "| block_seq | distinct roads | " + " | ".join(f"seed {s}" for s in seeds) + " |",
            "|---|---|" + "---|" * len(seeds),
        ]
        for block_seq, digests in sorted(variety.items()):
            marker = "" if len(set(digests)) == len(seeds) else "  **<**"
            lines.append(
                f"| `{block_seq}` | {len(set(digests))}/{len(seeds)}{marker} | "
                + " | ".join(f"`{d}`" for d in digests)
                + " |"
            )
        total = sum(len(set(d)) for d in variety.values())
        lines += [
            "",
            f"**{total} distinct roads across the {len(CATEGORIES) * len(seeds)} scenarios.**",
            "`X` has no seeded degree of freedom left: `StdInterSection` fixes its radius and the",
            "map pins `lane_num=3` and `lane_width=3.5`. Accepted deliberately -- the five seeds",
            "of an intersection category vary the scene, not the road. Phase 2 must therefore not",
            "assert one `map_id` per scenario, and at option level zero those five runs coincide.",
        ]
    lines.append("")
    return "\n".join(lines)


def write(path: Path, seeds: tuple[int, ...] = SEEDS) -> Path:
    """Measure everything and write the document. Costs two env builds per category per seed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(build_rows(seeds), seeds, measure_road_variety(seeds)))
    return path
