"""Writing `docs/reference/destinations.md` -- the record of which exit each category drives to.

The document is generated rather than hand-maintained, for the reason the house rules give: never
quote a measured figure, re-measure it. Every number in it comes from a reset on this simulator,
so regenerating it after a MetaDrive bump is how a change in block shape becomes visible.
"""

from __future__ import annotations

from pathlib import Path

from scenariobank.categories import CATEGORIES, SEEDS, step_budget
from scenariobank.sockets import survey


def measure_road_variety(seeds: tuple[int, ...] = SEEDS) -> dict[str, list[str]]:
    """Fingerprint the drivable surface of each block sequence at each seed.

    A seed is assumed to mean a different road, and for three of the five sequences it does
    not. Measuring it here, in the generated document, is what keeps that from being a
    surprise in Phase 2 -- or worse, an unexamined assumption in `CONTRACT.md`.
    """
    from metadrive.envs.metadrive_env import MetaDriveEnv

    from scenariobank.config import base_config

    sequences = sorted({category.block_seq for category in CATEGORIES.values()})
    variety = {}
    for block_seq in sequences:
        env = MetaDriveEnv(
            base_config(map=block_seq, start_seed=min(seeds), num_scenarios=len(seeds))
        )
        try:
            variety[block_seq] = [
                _digest_after_reset(env, seed) for seed in seeds
            ]
        finally:
            env.close()
    return variety


def _digest_after_reset(env, seed: int) -> str:
    from scenariobank.fingerprint import lane_geometry_digest

    env.reset(seed=seed)
    return lane_geometry_digest(env.engine.current_map, length=10)

HEADER = """# Destinations

Generated by `scenariobank destinations`. Do not edit by hand -- every figure here is
measured on the simulator `scenariobank doctor` reports, and regenerating after a MetaDrive bump
is how a change in block geometry becomes visible.

Angles are degrees from the ego's spawn heading, counter-clockwise-positive, so **positive is a
left turn** (`straight_lane.py:56`). `route_length` is `navigation.total_length` with the
destination pinned, which also proves the destination is reachable and not merely named.

**Two different angles appear below.** The resolved-destination table reports the *final heading*,
`wrap_to_pi`'d -- correct for choosing an exit, and what `ExitRule` matches against. "Turn taken"
reports **total rotation along the driven route**, which is not wrapped. They agree everywhere
except a route that sweeps past 180 degrees, where the wrapped one folds and changes sign: `curve`
seed 0 turns +239.5 degrees left and its final heading reads -120.5.
"""


def build_rows(seeds: tuple[int, ...] = SEEDS) -> dict[str, list[dict]]:
    """Resolve and measure every category at every seed."""
    return {name: survey(category, seeds) for name, category in CATEGORIES.items()}


def _spawn_lane_section(rows: dict[str, list[dict]], seeds: tuple[int, ...]) -> list[str]:
    """The spawn lane per seed -- the one thing a fixed road still varies.

    `random_spawn_lane_index` is left on deliberately (`config.base_config`), so the lane is a
    seeded draw rather than a constant. Measurement says it depends only on the seed, because
    every map is `lane_num=3` -- but that is **checked here rather than assumed**, and the full
    per-category table is emitted if it ever stops being true.
    """
    lanes = {
        name: [row["spawn_lane"] for row in category_rows]
        for name, category_rows in rows.items()
    }
    header = [
        "",
        "## Spawn lane",
        "",
        "Which of the three lanes the ego starts in. Drawn by `random_spawn_lane_index`, which",
        "this bank deliberately leaves on -- for `X` it is the *only* thing that differs between",
        "the five seeds, since the road is identical at all five. `route_length` is measured on a",
        "reference lane and so does not reflect it.",
        "",
    ]
    shared = next(iter(lanes.values()))
    if all(seq == shared for seq in lanes.values()):
        return header + [
            "| | " + " | ".join(f"seed {s}" for s in seeds) + " |",
            "|---|" + "---|" * len(seeds),
            "| every category | " + " | ".join(str(lane) for lane in shared) + " |",
            "",
            "Identical for every block sequence -- the draw is `randint(lane_num)` and every "
            f"map is `lane_num=3`, so it depends only on the seed. {len(set(shared))} distinct "
            f"starting lanes across these {len(seeds)} seeds.",
        ]
    return header + [
        "| category | " + " | ".join(f"seed {s}" for s in seeds) + " |",
        "|---|" + "---|" * len(seeds),
        *(
            f"| `{name}` | " + " | ".join(str(lane) for lane in seq) + " |"
            for name, seq in lanes.items()
        ),
        "",
        "**The spawn lane is no longer seed-only.** It used to depend on nothing but the seed;",
        "if this table is not uniform, a block sequence has changed its lane count.",
    ]


def _turn_pair_section(rows: dict[str, list[dict]], seeds: tuple[int, ...]) -> list[str]:
    """Which direction each `Curve` block turns, per seed.

    `CC` is two curves drawn independently, so the pair is the property that matters: two lefts
    and two rights are not enough on their own, the seeds have to reach left-then-right and
    right-then-left as well. `tests/unit/test_categories.py` asserts the coverage.
    """
    curved = {
        name: category_rows
        for name, category_rows in rows.items()
        if any(row["turn_pairs"] for row in category_rows)
    }
    if not curved:
        return []
    lines = [
        "",
        "## Curve direction pairs",
        "",
        "One letter per `Curve` block on the route, in order. The two blocks of `CC` draw their",
        "direction independently (`pg_space.py:284-289`), so the pair -- not the net angle -- is",
        "what says whether the seeds cover the manoeuvre.",
        "",
        "| category | " + " | ".join(f"seed {s}" for s in seeds) + " | combinations |",
        "|---|" + "---|" * len(seeds) + "---|",
    ]
    for name, category_rows in curved.items():
        signatures = [row["turn_pairs"] for row in category_rows]
        distinct = len(set(signatures))
        possible = 2 ** len(signatures[0])
        marker = "" if distinct == possible else "  **<**"
        lines.append(
            f"| `{name}` | "
            + " | ".join(f"`{sig}`" for sig in signatures)
            + f" | {distinct}/{possible}{marker} |"
        )
    lines += [
        "",
        "`L` is a left-turning block, `R` a right-turning one, measured from the built geometry",
        "rather than from `Parameter.dir` -- the map is mirrored (`handedness.py`), and a",
        "parameter reading would label every turn backwards.",
    ]
    return lines


def render(
    rows: dict[str, list[dict]],
    seeds: tuple[int, ...] = SEEDS,
    variety: dict[str, list[str]] | None = None,
) -> str:
    """Render the measured rows as the reference document."""
    lines = [HEADER, "## Resolved destination per category and seed", ""]
    lines.append("| category | block_seq | rule | " + " | ".join(f"seed {s}" for s in seeds) + " |")
    lines.append("|---|---|---|" + "---|" * len(seeds))
    for name, category in CATEGORIES.items():
        cells = [f"`{row['destination']}` {row['angle_deg']:+.0f}deg" for row in rows[name]]
        lines.append(
            f"| `{name}` | `{category.block_seq}` | `{category.exit_rule.value}` | "
            + " | ".join(cells)
            + " |"
        )

    lines += ["", "## Route length and step budget", ""]
    lines.append("| category | shortest | longest | `max_steps` | budget at longest |")
    lines.append("|---|---|---|---|---|")
    for name, category in CATEGORIES.items():
        lengths = [row["route_length_m"] for row in rows[name]]
        earned = step_budget(max(lengths))
        note = "" if category.max_steps >= earned else "  **under budget**"
        lines.append(
            f"| `{name}` | {min(lengths):.1f} m | {max(lengths):.1f} m | "
            f"{category.max_steps} | {earned}{note} |"
        )

    lines += [
        "",
        "`max_steps` is `step_budget(longest route)`: length / (6 m/s x 0.1 s per step) x 1.5,",
        "rounded up to 20. Provisional until Phase 4b measures what a policy actually needs.",
        "",
        "## Turn taken",
        "",
        "Total rotation along the route, unwrapped -- see the note above.",
        "",
        "| category | " + " | ".join(f"seed {s}" for s in seeds) + " |",
        "|---|" + "---|" * len(seeds),
    ]
    for name in CATEGORIES:
        cells = [f"{row['turn']} {row['net_rotation_deg']:+.1f}deg" for row in rows[name]]
        lines.append(f"| `{name}` | " + " | ".join(cells) + " |")

    lines += _spawn_lane_section(rows, seeds) + _turn_pair_section(rows, seeds)

    if variety is not None:
        lines += [
            "",
            "## Distinct roads per block sequence",
            "",
            "A seed does not always mean a different road. Fingerprints are of the drivable",
            "surface -- every lane centreline, sampled -- not of `get_meta_data()`, which",
            "carries `map_config.seed` and would make every road look unique.",
            "",
            "| block_seq | distinct roads | " + " | ".join(f"seed {s}" for s in seeds) + " |",
            "|---|---|" + "---|" * len(seeds),
        ]
        for block_seq, digests in sorted(variety.items()):
            marker = "" if len(set(digests)) == len(seeds) else "  **<**"
            lines.append(
                f"| `{block_seq}` | {len(set(digests))}/{len(seeds)}{marker} | "
                + " | ".join(f"`{d}`" for d in digests)
                + " |"
            )
        total = sum(len(set(d)) for d in variety.values())
        lines += [
            "",
            f"**{total} distinct roads across the {len(CATEGORIES) * len(seeds)} scenarios.**",
            "`X` has no seeded degree of freedom left: `StdInterSection` fixes its radius and the",
            "map pins `lane_num=3` and `lane_width=3.5`. Accepted deliberately -- the five seeds",
            "of an intersection category vary the scene, not the road. Phase 2 must therefore not",
            "assert one `map_id` per scenario.",
            "",
            "Those five runs are still not identical, though: the ego starts in a different lane",
            "(see **Spawn lane**), which is the only thing distinguishing them until Phase 3's",
            "options arrive.",
        ]
    lines.append("")
    return "\n".join(lines)


def write(path: Path, seeds: tuple[int, ...] = SEEDS) -> Path:
    """Measure everything and write the document. Costs two env builds per category per seed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(build_rows(seeds), seeds, measure_road_variety(seeds)))
    return path
